langfuse_public: "pk-lf-123"
langfuse_secret: "sk-lf-456"
langfuse_host: "http://localhost:3000"

redis:
  # For local dev/tests, use FakeRedis via the factory by setting testing: true
  # host: "localhost"
  # port: 6379
  testing: true

qdrant:
  # On-disk local Qdrant storage
  path: "./qdrant.db"
  # For remote Qdrant, provide url instead:
  # url: "http://localhost:6333"

eventing:
  # Kafka connection settings (defaults target docker-compose service `kafka`)
  bootstrap_servers: "localhost:9092"
  # Optional schema registry (Apicurio/Karapace) endpoint
  schema_registry_url: "http://localhost:8080"
  # Topics
  topics:
    memory_events: "memory.events"
    memory_audit: "memory.audit"
    memory_dlq: "memory.dlq"

memory_enterprise:
  # Vector dimension for embeddings
  vector_dim: 768
  # Background decay/pruning cadence (seconds)
  pruning_interval_seconds: 60
  # Multi-level time thresholds for field decay (seconds)
  decay_thresholds_seconds: [30, 300]
  # Keys to drop at each threshold level
  decayable_keys_by_level:
    - ["scratch", "temp_notes"]
    - ["low_importance"]
