services:
  # TEST API Server on port 9999
  test_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soma_test_api
    ports:
      - "9999:9595"
    environment:
      MEMORY_MODE: evented_enterprise
      SOMA_RATE_LIMIT_MAX: "5000"
      UVICORN_WORKERS: "2"
      UVICORN_TIMEOUT_GRACEFUL: "60"
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/somamemory_test
      REDIS_URL: redis://redis:6379/1  # Different Redis DB
      QDRANT_URL: http://qdrant:6333
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTING_ENABLED: "true"
      SOMA_MEMORY_NAMESPACE: test_ns
    depends_on:
      - redis
      - qdrant
      - postgres
      - kafka
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9595/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Consumer for TEST environment
  test_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soma_test_consumer
    command: ["python", "scripts/run_consumers.py"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_MEMORY_EVENTS_TOPIC: memory.events.test
      KAFKA_CONSUMER_GROUP: test-consumer-group
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/somamemory_test
      REDIS_URL: redis://redis:6379/1
      QDRANT_URL: http://qdrant:6333
      SOMA_MEMORY_NAMESPACE: test_ns
    depends_on:
      - redis
      - qdrant
      - postgres
      - kafka
    restart: unless-stopped

  # Infrastructure services (shared with DEV but different DBs/namespaces)
  postgres:
    image: postgres:15-alpine
    container_name: soma_test_postgres
    environment:
      POSTGRES_DB: somamemory_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: postgres -c 'shared_preload_libraries=pg_stat_statements'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.2.4-alpine
    container_name: soma_test_redis
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  qdrant:
    image: qdrant/qdrant:v1.9.2
    container_name: soma_test_qdrant
    volumes:
      - qdrant_test_storage:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka_test
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka_test:9093'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,OUTSIDE://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_test:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_JVM_PERFORMANCE_OPTS: '-Xms256m -Xmx512m'
      CLUSTER_ID: 'abcdefghijklmnopqrstuv'
    ports:
      - "19092:19092"
    volumes:
      - redpanda_test_data:/var/lib/kafka/data
    restart: unless-stopped

volumes:
  qdrant_test_storage:
  postgres_test_data:
  redis_test_data:
  redpanda_test_data:
