packages:
  - pytest==7.4.0
  - numpy==1.26.4
  - redis>=4.5.1
  - qdrant-client==1.2.2
  # Use CPU-only PyTorch wheels to avoid large CUDA artifacts in the image
  - -f https://download.pytorch.org/whl/cpu/torch_stable.html
  - torch==2.2.0+cpu
  - torchaudio==2.2.0+cpu
  - transformers==4.35.2
  - langfuse==0.5.0
  - scikit-learn==1.3.2
  - cryptography==41.0.3
  - prometheus-client==0.16.0
  - tenacity==8.2.2
  - structlog==23.1.0
  - dynaconf==4.4.0
  - Pillow==9.5.0
  - fakeredis>=2.0.0
  - networkx==3.1
    - networkx==3.1
