"""
Type stubs for Django model managers to resolve Pyright errors.
Django model managers like 'objects' are added dynamically at runtime.
"""

from typing import TYPE_CHECKING, Generic, TypeVar

if TYPE_CHECKING:
    from django.db import models

    _T = TypeVar("_T")

    class Manager(Generic[_T]):
        """Base manager type stub."""

        def all(self) -> models.QuerySet[_T]: ...
        def filter(self, **kwargs: object) -> models.QuerySet[_T]: ...
        def get(self, **kwargs: object) -> _T: ...
        def create(self, **kwargs: object) -> _T: ...
        def get_or_create(self, **kwargs: object) -> tuple[_T, bool]: ...
        def update_or_create(self, **kwargs: object) -> tuple[_T, bool]: ...
        def count(self) -> int: ...

    class QuerySet(Generic[_T]):
        """QuerySet type stub."""

        def all(self) -> models.QuerySet[_T]: ...
        def filter(self, **kwargs: object) -> models.QuerySet[_T]: ...
        def get(self, **kwargs: object) -> _T: ...
        def count(self) -> int: ...
        def first(self) -> _T | None: ...
        def last(self) -> _T | None: ...
        def exists(self) -> bool: ...
