{{- if .Values.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "somafractalmemory.fullname" . }}-consumer
  labels:
    {{- include "somafractalmemory.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumer.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "somafractalmemory.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: consumer
  template:
    metadata:
      labels:
        {{- include "somafractalmemory.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: consumer
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy | default "IfNotPresent" }}
          command: ["python", "scripts/run_consumers.py"]
          env:
            {{- range $key, $value := .Values.consumer.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.consumer.resources | nindent 12 }}
{{- end }}
