{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default (include "somafractalmemory.secretName" .) .Values.externalSecret.name }}
  labels:
    {{- include "somafractalmemory.labels" . | nindent 4 }}
  {{- with .Values.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ default "1h" .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "externalSecret.secretStoreRef.name is required when externalSecret.enabled=true" .Values.externalSecret.secretStoreRef.name }}
    {{- with .Values.externalSecret.secretStoreRef.kind }}
    kind: {{ . }}
    {{- end }}
  target:
    name: {{ default (include "somafractalmemory.secretName" .) .Values.externalSecret.target.name }}
    {{- with .Values.externalSecret.target.creationPolicy }}
    creationPolicy: {{ . }}
    {{- end }}
    {{- with .Values.externalSecret.target.deletionPolicy }}
    deletionPolicy: {{ . }}
    {{- end }}
    {{- with .Values.externalSecret.target.template }}
    template:
      {{- with .metadata }}
      metadata:
        {{- with .labels }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .type }}
      type: {{ . }}
      {{- end }}
      {{- with .engineVersion }}
      engineVersion: {{ . }}
      {{- end }}
      {{- with .data }}
      data:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      {{- with .stringData }}
      stringData:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- with .Values.externalSecret.data }}
  data:
    {{- range . }}
    - secretKey: {{ required "externalSecret.data[].secretKey is required" .secretKey }}
      remoteRef:
        key: {{ required "externalSecret.data[].remoteRef.key is required" .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
        {{- with .remoteRef.version }}
        version: {{ . }}
        {{- end }}
        {{- with .remoteRef.decodingStrategy }}
        decodingStrategy: {{ . }}
        {{- end }}
        {{- with .remoteRef.metadataPolicy }}
        metadataPolicy: {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- range . }}
    - extract:
        key: {{ required "externalSecret.dataFrom[].extract.key is required" .extract.key }}
    {{- end }}
  {{- end }}
{{- end }}
