{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  serviceName: {{ .Release.Name }}-kafka
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: "apache/kafka:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        resources:
{{ toYaml .Values.kafka.resources | indent 10 }}
        env:
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://{{ .Release.Name }}-kafka:9092"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_HEAP_OPTS
          value: {{ .Values.kafka.config.heapOpts | quote }}
        {{- if .Values.kafka.persistence.enabled }}
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        {{- end }}
  {{- if .Values.kafka.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kafka.persistence.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.kafka.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
{{- end }}
