apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-somafractalmemory
  labels:
    app: somafractalmemory
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9595 # The container port is fixed at 9595
      protocol: TCP
      name: http
  selector:
    app: somafractalmemory
