apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-somafractalmemory
  labels:
    app: somafractalmemory
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9393 # Kubernetes uses port 9393
      protocol: TCP
      name: http
  selector:
    app: somafractalmemory
