# Staging overlay for soma-infra.
postgres:
  postgresql:
    replicaCount: 2
    persistence:
      enabled: true
      size: 20Gi
      storageClass: premium-rwo
  pgpool:
    replicaCount: 2

redis:
  architecture: replication
  auth:
    enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClass: premium-rwo

kafka:
  controller:
    replicaCount: 3
    persistence:
      enabled: true
      size: 50Gi
      storageClass: premium-rwo

vault:
  enabled: true
  server:
    ha:
      enabled: true
    dataStorage:
      enabled: true
      size: 20Gi
      storageClass: premium-rwo

opa:
  enabled: true

prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 20Gi
      storageClass: premium-rwo
  alertmanager:
    enabled: true

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClass: premium-rwo
