# Production overlay for soma-infra.
postgres:
  postgresql:
    replicaCount: 3
    persistence:
      enabled: true
      size: 100Gi
      storageClass: premium-rwo
  pgpool:
    replicaCount: 3
    service:
      ports:
        postgresql: 5432

redis:
  architecture: replication
  auth:
    enabled: true
    password: ""
  persistence:
    enabled: true
    size: 50Gi
    storageClass: premium-rwo

kafka:
  controller:
    replicaCount: 3
    persistence:
      enabled: true
      size: 200Gi
      storageClass: premium-rwo
    metrics:
      jmx:
        enabled: true

vault:
  enabled: true
  server:
    ha:
      enabled: true
      replicas: 3
    dataStorage:
      enabled: true
      size: 50Gi
      storageClass: premium-rwo

opa:
  enabled: true
  admissionController:
    enabled: true

prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 200Gi
      storageClass: premium-rwo
  alertmanager:
    enabled: true

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 50Gi
    storageClass: premium-rwo
