# Test overlay for soma-infra.
postgres:
  postgresql:
    replicaCount: 1
    persistence:
      enabled: false
  pgpool:
    replicaCount: 1

redis:
  architecture: standalone
  persistence:
    enabled: false

kafka:
  controller:
    replicaCount: 1
    persistence:
      enabled: false

vault:
  enabled: false

opa:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false
