{{- if .Values.endpointsConfigMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (printf "%s-endpoints" (include "soma-infra.fullname" .)) .Values.endpointsConfigMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "soma-infra.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: "{{ printf "%s-postgres-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace }}"
  PGPOOL_HOST: "{{ printf "%s-postgres-pgpool.%s.svc.cluster.local" .Release.Name .Release.Namespace }}"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "{{ printf "%s-redis-master.%s.svc.cluster.local" .Release.Name .Release.Namespace }}"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "{{ printf "%s-kafka.%s.svc.cluster.local:9092" .Release.Name .Release.Namespace }}"
  VAULT_ADDR: "{{ printf "http://%s-vault.%s.svc.cluster.local:8200" .Release.Name .Release.Namespace }}"
  OPA_URL: "{{ printf "http://%s-opa.%s.svc.cluster.local:8181/v1/data" .Release.Name .Release.Namespace }}"
  PROMETHEUS_URL: "{{ printf "http://%s-prometheus-server.%s.svc.cluster.local:80" .Release.Name .Release.Namespace }}"
  GRAFANA_URL: "{{ printf "http://%s-grafana.%s.svc.cluster.local" .Release.Name .Release.Namespace }}"
{{- end }}
