apiVersion: v1
kind: Pod
metadata:
  name: port-forwarder
  namespace: soma-memory
  labels:
    app: port-forwarder
spec:
  containers:
  - name: kubectl-proxy
    image: bitnami/kubectl:latest
    command: ["kubectl"]
    args: ["proxy", "--address=0.0.0.0", "--accept-hosts=.*", "--port=8080"]
    ports:
    - containerPort: 8080
      protocol: TCP
  serviceAccountName: port-forwarder
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: port-forwarder
  namespace: soma-memory
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: port-forwarder
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: port-forwarder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: port-forwarder
subjects:
- kind: ServiceAccount
  name: port-forwarder
  namespace: soma-memory
---
apiVersion: v1
kind: Service
metadata:
  name: port-forwarder
  namespace: soma-memory
spec:
  type: NodePort
  selector:
    app: port-forwarder
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
