apiVersion: v1
kind: Service
metadata:
  name: somafractalmemory
  labels:
    app: somafractalmemory
spec:
  type: ClusterIP
  selector:
    app: somafractalmemory
  ports:
    - protocol: TCP
      port: 9595
      targetPort: 9595
