apiVersion: v1
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-bulk-1000-script
  namespace: soma
data:
  poster.py: |-
    import requests

    def post_chunk(start, end):
        items=[{"coord":f"{j},{j},{j}","payload":{"val":j,"run_id":"job-1000-run"},"type":"episodic"} for j in range(start,end)]
        r=requests.post('http://soma-memory-somafractalmemory:9595/store_bulk', json={'items':items}, timeout=120)
        print('chunk',start,'->',end,'status',r.status_code)

    for i in range(0,1000,100):
        post_chunk(i, min(i+100,1000))
    print('all done')

---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-bulk-1000
  namespace: soma
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: poster
        image: python:3.10-slim
        command: ["/bin/sh","-c"]
        args: ["pip install --no-cache-dir requests && python /script/poster.py"]
        volumeMounts:
        - name: script
          mountPath: /script
      volumes:
      - name: script
        configMap:
          name: post-bulk-1000-script
  ttlSecondsAfterFinished: 300
