# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in memory_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MemoryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Store = channel.unary_unary(
            "/somafractalmemory.MemoryService/Store",
            request_serializer=memory__pb2.StoreRequest.SerializeToString,
            response_deserializer=memory__pb2.StoreResponse.FromString,
            _registered_method=True,
        )
        self.Recall = channel.unary_unary(
            "/somafractalmemory.MemoryService/Recall",
            request_serializer=memory__pb2.RetrieveRequest.SerializeToString,
            response_deserializer=memory__pb2.RecallResult.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/somafractalmemory.MemoryService/Delete",
            request_serializer=memory__pb2.DeleteRequest.SerializeToString,
            response_deserializer=memory__pb2.DeleteResponse.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/somafractalmemory.MemoryService/Health",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=memory__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class MemoryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Store": grpc.unary_unary_rpc_method_handler(
            servicer.Store,
            request_deserializer=memory__pb2.StoreRequest.FromString,
            response_serializer=memory__pb2.StoreResponse.SerializeToString,
        ),
        "Recall": grpc.unary_unary_rpc_method_handler(
            servicer.Recall,
            request_deserializer=memory__pb2.RetrieveRequest.FromString,
            response_serializer=memory__pb2.RecallResult.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=memory__pb2.DeleteRequest.FromString,
            response_serializer=memory__pb2.DeleteResponse.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=memory__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "somafractalmemory.MemoryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("somafractalmemory.MemoryService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MemoryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Store(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/somafractalmemory.MemoryService/Store",
            memory__pb2.StoreRequest.SerializeToString,
            memory__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Recall(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/somafractalmemory.MemoryService/Recall",
            memory__pb2.RetrieveRequest.SerializeToString,
            memory__pb2.RecallResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/somafractalmemory.MemoryService/Delete",
            memory__pb2.DeleteRequest.SerializeToString,
            memory__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/somafractalmemory.MemoryService/Health",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            memory__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
