# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "memory.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cmemory.proto\x12\x11somafractalmemory\x1a\x1bgoogle/protobuf/empty.proto"\x1c\n\nCoordinate\x12\x0e\n\x06values\x18\x01 \x03(\x01"a\n\x06Memory\x12,\n\x05\x63oord\x18\x01 \x01(\x0b\x32\x1d.somafractalmemory.Coordinate\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\x12\x13\n\x0bmemory_type\x18\x03 \x01(\t"9\n\x0cStoreRequest\x12)\n\x06memory\x18\x01 \x01(\x0b\x32\x19.somafractalmemory.Memory"\'\n\rStoreResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t"c\n\x0fRetrieveRequest\x12,\n\x05query\x18\x01 \x01(\x0b\x32\x1d.somafractalmemory.Coordinate\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x13\n\x0bmemory_type\x18\x03 \x01(\t";\n\x0cRecallResult\x12+\n\x08memories\x18\x01 \x03(\x0b\x32\x19.somafractalmemory.Memory"=\n\rDeleteRequest\x12,\n\x05\x63oord\x18\x01 \x01(\x0b\x32\x1d.somafractalmemory.Coordinate"\x1c\n\x0e\x44\x65leteResponse\x12\n\n\x02ok\x18\x01 \x01(\x08" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbe\x02\n\rMemoryService\x12J\n\x05Store\x12\x1f.somafractalmemory.StoreRequest\x1a .somafractalmemory.StoreResponse\x12M\n\x06Recall\x12".somafractalmemory.RetrieveRequest\x1a\x1f.somafractalmemory.RecallResult\x12M\n\x06\x44\x65lete\x12 .somafractalmemory.DeleteRequest\x1a!.somafractalmemory.DeleteResponse\x12\x43\n\x06Health\x12\x16.google.protobuf.Empty\x1a!.somafractalmemory.HealthResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "memory_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_COORDINATE"]._serialized_start = 64
    _globals["_COORDINATE"]._serialized_end = 92
    _globals["_MEMORY"]._serialized_start = 94
    _globals["_MEMORY"]._serialized_end = 191
    _globals["_STOREREQUEST"]._serialized_start = 193
    _globals["_STOREREQUEST"]._serialized_end = 250
    _globals["_STORERESPONSE"]._serialized_start = 252
    _globals["_STORERESPONSE"]._serialized_end = 291
    _globals["_RETRIEVEREQUEST"]._serialized_start = 293
    _globals["_RETRIEVEREQUEST"]._serialized_end = 392
    _globals["_RECALLRESULT"]._serialized_start = 394
    _globals["_RECALLRESULT"]._serialized_end = 453
    _globals["_DELETEREQUEST"]._serialized_start = 455
    _globals["_DELETEREQUEST"]._serialized_end = 516
    _globals["_DELETERESPONSE"]._serialized_start = 518
    _globals["_DELETERESPONSE"]._serialized_end = 546
    _globals["_HEALTHRESPONSE"]._serialized_start = 548
    _globals["_HEALTHRESPONSE"]._serialized_end = 580
    _globals["_MEMORYSERVICE"]._serialized_start = 583
    _globals["_MEMORYSERVICE"]._serialized_end = 901
# @@protoc_insertion_point(module_scope)
