"""Module 0001_initial."""

# Generated by Django 6.0 on 2026-01-02 22:21

import uuid

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class implementation."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemoryNamespace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("tenant", models.CharField(db_index=True, default="default", max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Namespace-specific configuration"),
                ),
                ("total_memories", models.IntegerField(default=0)),
                ("episodic_count", models.IntegerField(default=0)),
                ("semantic_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Memory Namespace",
                "verbose_name_plural": "Memory Namespaces",
                "db_table": "sfm_namespaces",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("search", "Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("namespace", models.CharField(db_index=True, max_length=255)),
                ("coordinate_key", models.CharField(blank=True, max_length=512)),
                ("tenant", models.CharField(db_index=True, default="default", max_length=255)),
                ("user_id", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "sfm_audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["namespace", "action", "timestamp"],
                        name="sfm_audit_l_namespa_384878_idx",
                    ),
                    models.Index(
                        fields=["tenant", "timestamp"], name="sfm_audit_l_tenant_1f9dae_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GraphLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("namespace", models.CharField(db_index=True, max_length=255)),
                (
                    "from_coordinate",
                    django.contrib.postgres.fields.ArrayField(base_field=models.FloatField()),
                ),
                ("from_coordinate_key", models.CharField(max_length=512)),
                (
                    "to_coordinate",
                    django.contrib.postgres.fields.ArrayField(base_field=models.FloatField()),
                ),
                ("to_coordinate_key", models.CharField(max_length=512)),
                ("link_type", models.CharField(db_index=True, default="related", max_length=100)),
                ("strength", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tenant", models.CharField(db_index=True, default="default", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Graph Link",
                "verbose_name_plural": "Graph Links",
                "db_table": "sfm_graph_links",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["namespace", "from_coordinate_key"],
                        name="sfm_graph_l_namespa_61a38c_idx",
                    ),
                    models.Index(
                        fields=["namespace", "to_coordinate_key"],
                        name="sfm_graph_l_namespa_e06fa1_idx",
                    ),
                    models.Index(
                        fields=["namespace", "link_type"], name="sfm_graph_l_namespa_a5883e_idx"
                    ),
                    models.Index(
                        fields=["tenant", "namespace"], name="sfm_graph_l_tenant_75b2dd_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "namespace",
                            "from_coordinate_key",
                            "to_coordinate_key",
                            "link_type",
                        ),
                        name="unique_graph_link",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("namespace", models.CharField(db_index=True, max_length=255)),
                (
                    "coordinate",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), help_text="Memory coordinate as float array"
                    ),
                ),
                (
                    "coordinate_key",
                    models.CharField(
                        db_index=True,
                        help_text="Stringified coordinate for lookups",
                        max_length=512,
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        choices=[("episodic", "Episodic"), ("semantic", "Semantic")],
                        default="episodic",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tenant", models.CharField(db_index=True, default="default", max_length=255)),
                ("importance", models.FloatField(db_index=True, default=0.0)),
                ("access_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Memory",
                "verbose_name_plural": "Memories",
                "db_table": "sfm_memories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["namespace", "coordinate_key"],
                        name="sfm_memorie_namespa_7e7c85_idx",
                    ),
                    models.Index(
                        fields=["namespace", "memory_type"], name="sfm_memorie_namespa_dd06cb_idx"
                    ),
                    models.Index(
                        fields=["tenant", "namespace"], name="sfm_memorie_tenant_9f7485_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["payload"], name="sfm_memories_payload_gin"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("namespace", "coordinate_key"), name="unique_namespace_coordinate"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VectorEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("collection_name", models.CharField(max_length=255)),
                (
                    "milvus_id",
                    models.BigIntegerField(help_text="ID in Milvus collection", null=True),
                ),
                ("vector_dim", models.IntegerField(default=768)),
                ("model_name", models.CharField(default="microsoft/codebert-base", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "memory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="somafractalmemory.memory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vector Embedding",
                "verbose_name_plural": "Vector Embeddings",
                "db_table": "sfm_vector_embeddings",
                "indexes": [
                    models.Index(
                        fields=["collection_name", "milvus_id"],
                        name="sfm_vector__collect_909cbf_idx",
                    )
                ],
            },
        ),
    ]
