# Generated by Django 5.2.11 on 2026-02-19 13:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("somafractalmemory", "0003_tenant_scoped_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("key_prefix", models.CharField(db_index=True, max_length=12)),
                ("key_hash", models.CharField(max_length=64)),
                ("allowed_namespaces", models.JSONField(blank=True, default=list)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("rate_limit_rps", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_test", models.BooleanField(default=False)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("usage_count", models.BigIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "sfm_api_keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"], name="sfm_api_key_tenant_ac759b_idx"
                    ),
                    models.Index(
                        fields=["key_prefix", "key_hash"], name="sfm_api_key_key_pre_51868a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant", models.CharField(db_index=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("hour_bucket", models.DateTimeField(db_index=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("memory_store", "Memory Store"),
                            ("memory_recall", "Memory Recall"),
                            ("memory_delete", "Memory Delete"),
                            ("graph_link", "Graph Link"),
                            ("graph_query", "Graph Query"),
                            ("vector_search", "Vector Search"),
                        ],
                        max_length=50,
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                ("bytes_processed", models.BigIntegerField(default=0)),
                ("api_key_id", models.UUIDField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "verbose_name": "Usage Record",
                "verbose_name_plural": "Usage Records",
                "db_table": "sfm_usage_records",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "hour_bucket"], name="sfm_usage_r_tenant_aa9795_idx"
                    ),
                    models.Index(
                        fields=["tenant", "operation", "hour_bucket"],
                        name="sfm_usage_r_tenant_1b617b_idx",
                    ),
                ],
            },
        ),
    ]
