# Generated by Django 5.2.14 on 2026-10-04 01:36

from django.db import migrations, models

import somafractalmemory.admin.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("somafractalmemory", "0006_drop_apikey_usagerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorembedding",
            name="model_name",
            field=models.CharField(default="hash-embedder", max_length=255),
        ),
        migrations.AlterField(
            model_name="vectorembedding",
            name="vector_dim",
            field=models.IntegerField(
                default=somafractalmemory.admin.core.models._default_vector_dim
            ),
        ),
    ]
