# Generated by Django 5.2.9 on 2026-10-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("somafractalmemory", "0007_honest_vector_embedding_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorynamespace",
            name="belief_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="memory",
            name="memory_type",
            field=models.CharField(
                choices=[("episodic", "Episodic"), ("semantic", "Semantic"), ("belief", "Belief")],
                default="episodic",
                max_length=20,
            ),
        ),
    ]
