# Development override: run API on port 9797 instead of default 9595.
service:
  type: NodePort
  port: 9797
  nodePort: 30797

env:
  UVICORN_PORT: "9797"
  SOMA_RATE_LIMIT_MAX: "5000"
  EVENTING_ENABLED: "false"
  REDIS_HOST: "soma-memory-somafractalmemory-redis"
  REDIS_PORT: "6379"
  QDRANT_HOST: "soma-memory-somafractalmemory-qdrant"
  QDRANT_PORT: "6333"

secret:
  data:
    SOMA_API_TOKEN: "changeme-dev-token"
    POSTGRES_URL: "postgresql://postgres:postgres@soma-memory-somafractalmemory-postgres:5432/somamemory"
    REDIS_URL: "redis://soma-memory-somafractalmemory-redis:6379/0"
    QDRANT_URL: "http://soma-memory-somafractalmemory-qdrant:6333"
    KAFKA_BOOTSTRAP_SERVERS: "soma-memory-somafractalmemory-redpanda:9092"

probe:
  port: 9797
  path: /healthz

# Ensure the locally built image is used without attempting a remote pull.
image:
  pullPolicy: Never

consumer:
  enabled: false
  image:
    pullPolicy: Never

redpanda:
  enabled: false
