# Low‑resource overrides for Kind (local) clusters
# Keeps persistence enabled but uses modest PVC sizes so the local host can handle them.

# Global image override (local build)
image:
  repository: somafractalmemory
  tag: local
  pullPolicy: IfNotPresent

# Consumer configuration – uses the same local image as the API.
consumer:
  image:
    repository: somafractalmemory
    tag: local
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "150m"
      memory: "384Mi"
    limits:
      cpu: "600m"
      memory: "768Mi"

# API pod resources (main deployment)
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "800m"
    memory: "1Gi"

postgres:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
    limits:
      cpu: "800m"
      memory: "1Gi"

redis:
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"

qdrant:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  resources:
    requests:
      cpu: "250m"
      memory: "384Mi"
    limits:
      cpu: "750m"
      memory: "768Mi"

redpanda:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1500m"
      memory: "2Gi"

env:
  UVICORN_WORKERS: "1"
