name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint-test:
    name: Lint & Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Install tooling deps
        run: |
          pip install ruff black bandit mypy mkdocs mkdocs-material pip-audit
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Static security scan (bandit)
        run: bandit -q -r somafractalmemory scripts workers eventing
      - name: Type check (mypy)
        run: mypy somafractalmemory
      - name: Unit tests
        run: pytest -q -k "not full_infra_e2e and not kafka_event_flow"
      - name: Targeted integration test
        run: pytest -q tests/test_postgres_redis_hybrid_store.py
        continue-on-error: true
      - name: pip-audit
        run: pip-audit --requirement requirements.txt --requirement requirements-runtime.txt || echo "pip-audit found vulnerabilities (non-blocking)"
        continue-on-error: true
      - name: Build documentation (MkDocs)
        run: mkdocs build

  container-security:
    name: Container Build & Scan
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build runtime image
        run: docker build -f Dockerfile.runtime -t somafractalmemory:ci .
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: somafractalmemory:ci
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '0'
        continue-on-error: true
