name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests (unit)
        run: pytest -q
      - name: Run integration test for PostgresRedisHybridStore
        # This runs after unit tests; testcontainers will spin up Docker containers.
        run: pytest -q tests/test_postgres_redis_hybrid_store.py
      # Ensure Docker is available for testcontainers (GitHub runners already have Docker, but we expose it explicitly)
      - name: Verify Docker availability
        run: docker version
      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check .
      - name: Format check (black)
        run: |
          pip install black
          black --check .
      - name: Security scan (bandit)
        run: |
          pip install bandit
          bandit -q -r somafractalmemory
      - name: Type check (mypy)
        run: |
          pip install mypy
          mypy somafractalmemory
      - name: Build documentation (MkDocs)
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build
