name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          pip install -r requirements.txt
      - name: Lint
        run: |
          ruff check .
      - name: Type check
        run: |
          mypy || true
      - name: Test
        run: |
          pytest -q
name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests
        run: pytest -q
      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check .
      - name: Format check (black)
        run: |
          pip install black
          black --check .
      - name: Security scan (bandit)
        run: |
          pip install bandit
          bandit -q -r somafractalmemory
      - name: Type check
        run: |
          pip install mypy
          mypy somafractalmemory
